version: "3"

services:
  redis:
    restart: always
    image: redis:7.0.4
    networks:
      - nextcloud
  postgres:
    restart: always
    image: postgres:13
    networks:
      - nextcloud
    env_file:
      - postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
  nextcloud:
    restart: always
    depends_on:
      - redis
      - postgres
    image: nextcloud
    volumes:
      - nextcloud-files:/var/www/html
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
    networks:
      - nextcloud
    env_file:
      - nextcloud.env
  nginx:
    restart: always
    depends_on:
      - nextcloud
    build:
      context: nginx
    ports:
      - 443:443
      - 80:80
    networks:
      - nextcloud


volumes:
  postgres:
  nextcloud-files:
  nextcloud-data:
  nextcloud-config:
  nextcloud-apps:
networks:
  nextcloud: